name: NSCarpentry
favicon: null
layout_spectrum: 0.2805169322527945
typography_spectrum: 0.5466522246133536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10667797713540494
  lightness: 0.4861174584366381
  saturation: 0.6738145330455154
  rhythmicContrast: 0.979713695589453
purpose: []
